"""
Binance Quant Trader V2 - ATR Strategy
========================================
ATR (Average True Range) based strategy for entry signals,
stop loss, take profit, and trailing stop calculations.
"""

import logging
import numpy as np
from typing import Optional
from dataclasses import dataclass

logger = logging.getLogger("trader.atr")


@dataclass
class ATRSignal:
    """Trading signal generated by ATR strategy."""
    symbol: str
    signal: str  # "LONG", "SHORT", "CLOSE_LONG", "CLOSE_SHORT", "HOLD"
    entry_price: float
    atr_value: float
    stop_loss: float
    take_profit: float
    trailing_stop: float
    confidence: float  # 0.0 - 1.0
    reason: str


class ATRCalculator:
    """Calculates ATR and generates trading signals."""

    def __init__(self, config):
        self.config = config
        self._kline_cache: dict[str, list] = {}
        self._last_signal: dict[str, ATRSignal] = {}
        self._mark_prices: dict[str, float] = {}

    def update_mark_price(self, symbol: str, price: float):
        """Update current mark price from WebSocket."""
        self._mark_prices[symbol] = price

    def update_klines(self, symbol: str, klines: list):
        """
        Update kline cache. klines format from Binance:
        [open_time, open, high, low, close, volume, close_time, ...]
        """
        self._kline_cache[symbol] = klines

    def calculate_atr(self, symbol: str) -> Optional[float]:
        """Calculate ATR from cached klines."""
        klines = self._kline_cache.get(symbol)
        if not klines or len(klines) < self.config.atr.atr_period + 1:
            return None

        period = self.config.atr.atr_period
        highs = np.array([float(k[2]) for k in klines[-(period + 1):]])
        lows = np.array([float(k[3]) for k in klines[-(period + 1):]])
        closes = np.array([float(k[4]) for k in klines[-(period + 1):]])

        # True Range = max(H-L, |H-prevC|, |L-prevC|)
        tr_list = []
        for i in range(1, len(highs)):
            tr = max(
                highs[i] - lows[i],
                abs(highs[i] - closes[i - 1]),
                abs(lows[i] - closes[i - 1])
            )
            tr_list.append(tr)

        if len(tr_list) < period:
            return None

        atr = float(np.mean(tr_list[-period:]))
        return atr

    def calculate_ema(self, symbol: str, period: int = 20) -> Optional[float]:
        """Calculate EMA from cached klines."""
        klines = self._kline_cache.get(symbol)
        if not klines or len(klines) < period:
            return None

        closes = np.array([float(k[4]) for k in klines[-period * 2:]])
        if len(closes) < period:
            return None

        # EMA calculation
        multiplier = 2.0 / (period + 1)
        ema = float(closes[0])
        for price in closes[1:]:
            ema = (float(price) - ema) * multiplier + ema
        return ema

    def calculate_bollinger(self, symbol: str, period: int = 20, std_dev: float = 2.0):
        """Calculate Bollinger Bands."""
        klines = self._kline_cache.get(symbol)
        if not klines or len(klines) < period:
            return None, None, None

        closes = np.array([float(k[4]) for k in klines[-period:]])
        sma = float(np.mean(closes))
        std = float(np.std(closes))
        upper = sma + std_dev * std
        lower = sma - std_dev * std
        return upper, sma, lower

    def generate_signal(self, symbol: str, current_position_amt: float = 0) -> Optional[ATRSignal]:
        """
        Generate trading signal based on ATR, EMA, and Bollinger Bands.

        Strategy logic:
        - LONG: Price below lower Bollinger + EMA trending up + ATR breakout
        - SHORT: Price above upper Bollinger + EMA trending down + ATR breakout
        - CLOSE_LONG: Price hits stop loss or take profit
        - CLOSE_SHORT: Price hits stop loss or take profit
        """
        atr = self.calculate_atr(symbol)
        if atr is None or atr <= 0:
            return None

        mark_price = self._mark_prices.get(symbol)
        if mark_price is None:
            return None

        ema_short = self.calculate_ema(symbol, 10)
        ema_long = self.calculate_ema(symbol, 30)
        bb_upper, bb_mid, bb_lower = self.calculate_bollinger(symbol)

        if ema_short is None or ema_long is None or bb_upper is None:
            return None

        cfg = self.config.atr
        stop_loss_dist = cfg.atr_sl_multiplier * atr
        take_profit_dist = cfg.atr_tp_multiplier * atr
        trailing_dist = cfg.atr_trailing_multiplier * atr

        # === Check existing position management ===
        last = self._last_signal.get(symbol)

        if current_position_amt > 0 and last:
            # LONG position - check exit conditions
            if mark_price <= last.stop_loss:
                return ATRSignal(
                    symbol=symbol, signal="CLOSE_LONG",
                    entry_price=mark_price, atr_value=atr,
                    stop_loss=0, take_profit=0, trailing_stop=0,
                    confidence=1.0, reason="ATR stop loss hit"
                )
            if mark_price >= last.take_profit:
                return ATRSignal(
                    symbol=symbol, signal="CLOSE_LONG",
                    entry_price=mark_price, atr_value=atr,
                    stop_loss=0, take_profit=0, trailing_stop=0,
                    confidence=1.0, reason="ATR take profit hit"
                )
            # Trailing stop for long
            new_trailing = mark_price - trailing_dist
            if new_trailing > last.trailing_stop:
                last.trailing_stop = new_trailing
            if mark_price <= last.trailing_stop:
                return ATRSignal(
                    symbol=symbol, signal="CLOSE_LONG",
                    entry_price=mark_price, atr_value=atr,
                    stop_loss=0, take_profit=0, trailing_stop=last.trailing_stop,
                    confidence=0.9, reason="ATR trailing stop hit"
                )

        elif current_position_amt < 0 and last:
            # SHORT position - check exit conditions
            if mark_price >= last.stop_loss:
                return ATRSignal(
                    symbol=symbol, signal="CLOSE_SHORT",
                    entry_price=mark_price, atr_value=atr,
                    stop_loss=0, take_profit=0, trailing_stop=0,
                    confidence=1.0, reason="ATR stop loss hit"
                )
            if mark_price <= last.take_profit:
                return ATRSignal(
                    symbol=symbol, signal="CLOSE_SHORT",
                    entry_price=mark_price, atr_value=atr,
                    stop_loss=0, take_profit=0, trailing_stop=0,
                    confidence=1.0, reason="ATR take profit hit"
                )
            # Trailing stop for short
            new_trailing = mark_price + trailing_dist
            if new_trailing < last.trailing_stop:
                last.trailing_stop = new_trailing
            if mark_price >= last.trailing_stop:
                return ATRSignal(
                    symbol=symbol, signal="CLOSE_SHORT",
                    entry_price=mark_price, atr_value=atr,
                    stop_loss=0, take_profit=0, trailing_stop=last.trailing_stop,
                    confidence=0.9, reason="ATR trailing stop hit"
                )

        # === Entry signals (only if no position) ===
        if current_position_amt != 0:
            return ATRSignal(symbol=symbol, signal="HOLD", entry_price=mark_price,
                           atr_value=atr, stop_loss=0, take_profit=0, trailing_stop=0,
                           confidence=0, reason="Position already open")

        # LONG signal: price near lower band + short EMA > long EMA (uptrend)
        long_confidence = 0.0
        long_reasons = []
        if mark_price <= bb_lower:
            long_confidence += 0.4
            long_reasons.append("price_below_lower_bb")
        if ema_short > ema_long:
            long_confidence += 0.3
            long_reasons.append("ema_uptrend")
        # ATR volatility confirmation
        klines = self._kline_cache.get(symbol, [])
        if len(klines) >= 2:
            last_close = float(klines[-1][4])
            prev_close = float(klines[-2][4])
            if last_close > prev_close:
                long_confidence += 0.2
                long_reasons.append("bullish_candle")
        if mark_price < ema_short:
            long_confidence += 0.1
            long_reasons.append("below_short_ema")

        # SHORT signal: price near upper band + short EMA < long EMA (downtrend)
        short_confidence = 0.0
        short_reasons = []
        if mark_price >= bb_upper:
            short_confidence += 0.4
            short_reasons.append("price_above_upper_bb")
        if ema_short < ema_long:
            short_confidence += 0.3
            short_reasons.append("ema_downtrend")
        if len(klines) >= 2:
            last_close = float(klines[-1][4])
            prev_close = float(klines[-2][4])
            if last_close < prev_close:
                short_confidence += 0.2
                short_reasons.append("bearish_candle")
        if mark_price > ema_short:
            short_confidence += 0.1
            short_reasons.append("above_short_ema")

        # Choose best signal
        signal = "HOLD"
        confidence = 0.0
        reasons = []
        sl_price = 0.0
        tp_price = 0.0

        MIN_CONFIDENCE = 0.6

        if long_confidence >= MIN_CONFIDENCE and long_confidence > short_confidence:
            signal = "LONG"
            confidence = long_confidence
            reasons = long_reasons
            sl_price = mark_price - stop_loss_dist
            tp_price = mark_price + take_profit_dist
        elif short_confidence >= MIN_CONFIDENCE and short_confidence > long_confidence:
            signal = "SHORT"
            confidence = short_confidence
            reasons = short_reasons
            sl_price = mark_price + stop_loss_dist
            tp_price = mark_price - take_profit_dist

        if signal != "HOLD":
            result = ATRSignal(
                symbol=symbol, signal=signal,
                entry_price=mark_price, atr_value=atr,
                stop_loss=sl_price, take_profit=tp_price,
                trailing_stop=sl_price,  # Initial trailing = stop loss
                confidence=confidence,
                reason=" | ".join(reasons)
            )
            self._last_signal[symbol] = result
            return result

        return ATRSignal(
            symbol=symbol, signal="HOLD",
            entry_price=mark_price, atr_value=atr,
            stop_loss=0, take_profit=0, trailing_stop=0,
            confidence=0, reason="No signal"
        )

    def get_atr_value(self, symbol: str) -> Optional[float]:
        return self.calculate_atr(symbol)

    def get_mark_price(self, symbol: str) -> Optional[float]:
        return self._mark_prices.get(symbol)
